pipeline-folder: "/users/fischerd/git/Pipeline-Metagenome"
project-folder: "/scratch/project_2006153/CO2"                                               # Path to the project folder
rawdata-folder: "/scratch/project_2006153/CO2/FASTQ/RAW" 
server-config: "/users/fischerd/git/Pipeline-Metagenome/Pipeline-Metagenome_server_config.yaml"
samplesheet: "/scratch/project_2006153/CO2/samplesheet.tsv"
local-scratch: $LOCAL_SCRATCH
contamination-folder: "/scratch/project_2006153/CO2/Contamination/"
contamination-refs: ["ARS-UCD1.2_Btau5.0.1Y.fa"]

urls:
    host: ""

params:
  fastp:
    trim_front1: 12
    trim_tail1: 0
    trim_front2: 0
    trim_tail2: 0
  fastqc:
    threads: 20
  star:
    overhang: 149
    limitGenomeGenerateRAM: 300647710720
singularity:
  fastp: "docker://fischuu/fastp:0.20.1"
  star: "docker://fischuu/star:2.7.5a"
  wgs: "docker://fischuu/wgs:0.2"
  r-gbs: "docker://fischuu/r-gbs:4.2.1-0.1"
  megahit: "docker://fischuu/megahit:1.2.9-0.2"
  bowtie2: "docker://fischuu/bowtie2:2.4.4-0.1"
  prodigal: "docker://fischuu/prodigal:2.6.3-0.1"