__default__:
    time: 00:30:00
    job-name:  SM_Metagenome
    account: project_2006153
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2006153/logs/
    nvme: 0

# Step1 - Preparations
################################################################################
star_create_host_index:
    job-name: star_create_index
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

# Step2 - ReadProcessing
################################################################################
Concatenate_lanes:
    job-name: Concatenate_lanes
    time: 04:00:00
    mem-per-cpu: 16000
    cpus-per-task: 1
    
fastp_trim_reads:
    job-name: Trim_data
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20
    
star_map_reads_host:
    job-name: star_map_reads_host
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

concatenate_inputfiles_cat:
    job-name:  concatenate_inputfiles_cat
    time: 2-00:00:00
    mem-per-cpu: 64000
    cpus-per-task: 1

build_contamination_indices:
    job-name: build_contamination_indices
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

star_decontaminate_reads:
    job-name: star_decontaminate_reads
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

# Step 3 - 
################################################################################
assemble_contigs_megahit:
    job-name: assemble_contigs_megahit
    time: 14-00:00:00
    mem-per-cpu: 60000
    cpus-per-task: 20
    partition: hugemem_longrun

filter_length_megahit:
    job-name: filter_length_megahit
    time: 04:00:00
    mem-per-cpu: 64000
    cpus-per-task: 1

create_index_bowtie2:
    job-name: create_index_bowtie2
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

map_data_metagenome_bowtie2:
    job-name: map_data_metagenome_bowtie2
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

samToBam_data_metagenome:
    job-name: samToBam_data_metagenome
    time: 01:00:00
    mem-per-cpu: 32000
    cpus-per-task: 1
    
# Step 4 -
################################################################################
prodigal_gene_prediction:
    job-name: prodigal_gene_prediction
    time: 1-00:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

cut_prodigal_bash:
    job-name: cut_prodigal_bash
    time: 04:00:00
    mem-per-cpu: 16000
    cpus-per-task: 1

prepare_eggnog_database:
    job-name: prepare_eggnog_database
    time: 04:00:00
    mem-per-cpu: 16000
    cpus-per-task: 1
    
eggnog_find_homology_parallel:
    job-name: eggnog_find_homology_parallel
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20
    nvme: 180
    
eggnog_orthology:
    job-name: eggnog_orthology
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20
    nvme: 180
    
quantify_predictedGenes_featureCounts:
    job-name: quantify_predictedGenes_featureCounts
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20
    
# Step 5- MAGs
################################################################################
cut_filtered_contigs_concoct:
    job-name: cut_filtered_contigs_concoct
    time: 04:00:00
    mem-per-cpu: 16000
    cpus-per-task: 1
    
process_covTable_bed_parallel:
    job-name: process_covTable_bed_parallel
    time: 04:00:00
    mem-per-cpu: 16000
    cpus-per-task: 1
    

process_covTable_bed_parallel_1k:
    job-name: process_covTable_bed_parallel_1k
    time: 04:00:00
    mem-per-cpu: 192000
    cpus-per-task: 1

process_covTable_bed_parallel_2k:
    job-name: process_covTable_bed_parallel_2k
    time: 04:00:00
    mem-per-cpu: 192000
    cpus-per-task: 1

run_concoct_1k:
    job-name: run_concoct_1k
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 40
    
run_concoct_2k:
    job-name: run_concoct_2k
    time: 04:00:00
    mem-per-cpu: 4000
    cpus-per-task: 40
    
extract_fasta_concoct_1k:
    job-name: extract_fasta_concoct_1k
    time: 04:00:00
    mem-per-cpu: 32000
    cpus-per-task: 1
    
extract_fasta_concoct_2k:
    job-name: extract_fasta_concoct_2k
    time: 04:00:00
    mem-per-cpu: 32000
    cpus-per-task: 1    
    
